#My Own Drawing

import turtle
window = turtle.Screen()
window.title('A Christmas Present')

window.bgcolor('antique white')

box = turtle.Turtle()
box.color('DarkSeaGreen', 'DarkSeaGreen')
box.pensize(4)

ribbon = turtle.Turtle()
ribbon.color('red', 'red')
ribbon.pensize(4)

star = turtle.Turtle()
star.color('gold')
star.pensize(3)

box.begin_fill() #This is the present itself
box.forward(100)
box.left(90)
box.forward(100)
box.left(90)
box.forward(100)
box.left(90)
box.forward(100)
box.end_fill()


ribbon.penup() #This segment of the ribbon is the ribbon that surrounds the present
ribbon.forward(33)
ribbon.pendown()
ribbon.begin_fill()
ribbon.forward(33)
ribbon.left(90)
ribbon.forward(33)
ribbon.right(90)
ribbon.forward(33)
ribbon.left(90)
ribbon.forward(33)
ribbon.left(90)
ribbon.forward(33)
ribbon.right(90)
ribbon.forward(33)
ribbon.left(90)
ribbon.forward(33)
ribbon.left(90)
ribbon.forward(33)
ribbon.right(90)
ribbon.forward(33)
ribbon.left(90)
ribbon.forward(33)
ribbon.left(90)
ribbon.forward(33)
ribbon.right(90)
ribbon.forward(33)
ribbon.end_fill()


ribbon.left(90)
ribbon.forward(10)
ribbon.left(90)
ribbon.forward(120)
ribbon.left(5)
ribbon.circle(15) #These circles will be the bow on top
ribbon.right(90)
ribbon.circle(15)
ribbon.right(90)
ribbon.circle(15)
ribbon.right(90)
ribbon.circle(15)
ribbon.penup()
ribbon.right(180)
ribbon.forward(20)
ribbon.pendown()
ribbon.left(90)
ribbon.circle(15)
ribbon.right(90)
ribbon.circle(15)
ribbon.right(90)
ribbon.circle(15)
ribbon.right(90)
ribbon.circle(15)

#And some stars just for fun
star.penup()
star.forward(150)
star.pendown()
star.right(36)
star.forward(100)
star.right(144)
star.forward(100)
star.right(144)
star.forward(100)
star.right(144)
star.forward(100)
star.right(144)
star.forward(100)

star.penup()
star.right(90)
star.forward(100)
star.right(180)
star.forward(50)
star.right(90)
star.forward(30)
star.pendown()
star.right(36)
star.forward(100)
star.right(144)
star.forward(100)
star.right(144)
star.forward(100)
star.right(144)
star.forward(100)
star.right(144)
star.forward(100)

window.mainloop()
